### ISSUE TITLE
Error in IPC handler: Error: [handleZIP] Error handling zip file

### ISSUE THREAD

**Issue by seanlawrenz** [dakota-kallas/DeskThing-GitHub#2]
**Describe the bug**
Desktop thing app is unable to unzip this repo.

**To Reproduce**
Download this repo zipped. Click upload app on desktop thing. Monitor the `Notifications`

**Expected behavior**
Well, I should be able to upload this app.

**Screenshots**
<img width="650" alt="Screenshot 2024-11-25 at 11 00 00 AM" src="https://github.com/user-attachments/assets/936f7ca9-0dc1-4e40-b0d8-699b3b7f670e">

**DeskThing (please complete the following information):**
 - Hardware: [e.g. Car Thing]
 - Version [e.g. 0.9.3]
 - GitHub App Version [e.g. 1.0.1]

**Comment by dakota-kallas** [comment]
Make sure you are uploading the `github-app-v1.0.0.zip` file.
![image](https://github.com/user-attachments/assets/cf5a0a98-03c3-4962-b8ba-e91266d578db)
